#pragma once

#define IDS_CLASS_NAME          1
#define IDS_CLASS_DESC          2
#define IDS_CATEGORY            3
#define IDS_PARAMETERS          4
#define IDS_LIBDESCRIPTION      5
#define IDS_ITERATIONS          6
#define IDS_SMOOTHNESS          7
#define IDS_USE_VERTEX_CREASE   8
#define IDS_USE_EDGE_CREASE     9
#define IDS_SMOOTH_RESULT       10
#define IDS_USE_RENDER_ITERS    11
#define IDS_RENDER_ITERS        12
#define IDS_ISOLINE_DISPLAY     13
#define IDS_VERTEX_BOUNDARY     14
#define IDS_FVAR_BOUNDARY       15
#define IDS_SMOOTH_TRIANGLES    16
#define IDS_CREASE_METHOD       17
#define IDS_VTX_EDGE_ONLY       18
#define IDS_VTX_EDGE_CORNER     19
#define IDS_FVAR_NONE           20
#define IDS_FVAR_CORNERS        21
#define IDS_FVAR_CORNERS_PLUS1  22
#define IDS_FVAR_CORNERS_PLUS2  23
#define IDS_FVAR_BOUNDARIES     24
#define IDS_FVAR_ALL            25
#define IDS_CREASE_UNIFORM      26
#define IDS_CREASE_CHAIKIN      27
#define IDS_WN_AREA             28
#define IDS_WN_ANGLE            29
#define IDS_WN_CONVEX           30
#define IDS_WN_SNAP             31
#define IDS_WN_BLENDING         32
#define IDS_WN_SMOOTH_GROUPS    33
#define IDS_WN_UV_SEAMS         34
#define IDS_WN_UV_CHANNEL       35
#define IDS_WN_HARD_ANGLE_USE   36
#define IDS_WN_HARD_ANGLE       37
#define IDS_WN_SMOOTHING        38
#define IDS_WN_BOUNDARY_BLEND   39
#define IDS_WN_ITERATIONS       40
#define IDS_WN_RELAXATION       41
#define IDS_WN_COPLANAR_AREA    42
#define IDS_WN_ROLLOUT          43
#define IDS_WN_DISPLAY_NORMALS  44
#define IDS_WN_NORMAL_LENGTH    45
#define IDS_DISPLAY_HARD_EDGES  46
#define IDS_HARD_EDGE_COLOR     47

#define IDD_MESHSMOOTHPRO       101
#define IDD_WEIGHTED_NORMALS    102
#define IDC_ITERATIONS          1001
#define IDC_ITERATIONS_SPIN     1002
#define IDC_SMOOTHNESS          1003
#define IDC_SMOOTHNESS_SPIN     1004
#define IDC_USE_VERTEX_CREASE   1005
#define IDC_USE_EDGE_CREASE     1006
#define IDC_SMOOTH_RESULT       1007
#define IDC_USE_RENDER_ITERS    1008
#define IDC_RENDER_ITERS        1009
#define IDC_RENDER_ITERS_SPIN   1010
#define IDC_ISOLINE_DISPLAY     1011
#define IDC_VERTEX_BOUNDARY     1012
#define IDC_FVAR_BOUNDARY       1013
#define IDC_SMOOTH_TRIANGLES    1014
#define IDC_CREASE_METHOD       1015
#define IDC_WN_AREA             1016
#define IDC_WN_ANGLE            1017
#define IDC_WN_CONVEX           1018
#define IDC_WN_SNAP             1019
#define IDC_WN_BLENDING         1020
#define IDC_WN_BLENDING_SPIN    1021
#define IDC_WN_SMOOTH_GROUPS    1022
#define IDC_WN_UV_SEAMS         1023
#define IDC_WN_UV_CHANNEL       1024
#define IDC_WN_UV_CHANNEL_SPIN  1025
#define IDC_WN_HARD_ANGLE_USE   1026
#define IDC_WN_HARD_ANGLE       1027
#define IDC_WN_HARD_ANGLE_SPIN  1028
#define IDC_WN_SMOOTHING        1029
#define IDC_WN_SMOOTHING_SPIN   1030
#define IDC_WN_BOUNDARY_BLEND   1031
#define IDC_WN_BOUNDARY_SPIN    1032
#define IDC_WN_ITERATIONS       1033
#define IDC_WN_ITERATIONS_SPIN  1034
#define IDC_WN_RELAXATION       1035
#define IDC_WN_RELAXATION_SPIN  1036
#define IDC_WN_COPLANAR_AREA    1037
